trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pr:
  - master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: 10.x

- script: npm ci
- script: npm test

- task: Npm@1
  inputs:
    command: 'publish'
    publishEndpoint: npmjs
  condition: and(succeeded(), eq(variables['JT_RELEASE'], '1'))
