trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pr:
  - master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: 10.x

- script: npm ci
- script: npm test

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
    customEndpoint: npmjs
  condition: and(succeeded(), eq(variables['JSONTALK_NPM_PUBLISH'], '1'))

- script: npm publish
  condition: and(succeeded(), eq(variables['JSONTALK_NPM_PUBLISH'], '1'))
